[project]
name = "del-duktek-copilot"
version = "0.1.0"
description = "Asisten cerdas berbasis AI untuk klasifikasi, prioritas, dan penyelesaian laporan Dukungan Teknis (Duktek) IT Del."
authors = [
    { name = "Rotua Immanuela Tampubolon", email = "rotuaimmanuela@gmail.com" },
    { name = "Olivia Tambunan", email = "olivtmbn@gmail.com" },
    { name = "Adryan Julianto Panjaitan", email = "andryanpanjaitan30@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.11.2",
]

[project.scripts]
del-duktek-copilot = "del_duktek_copilot:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
